spring.application.name=api-rest

#Banco H2 - configurações iniciais (Revisar!!!)
spring.datasource.url=jdbc:h2:mem:boazidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Criação automática das tabelas com base nas entidades JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita o console visual do H2 em http://localhost:8080/h2-console
spring.h2.console.enabled=true